// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2hREknnXIaDYEQj58_U6jcNsbJRwCtQ',
    appId: '1:580821940359:web:d49b97e5ad04eecac92022',
    messagingSenderId: '580821940359',
    projectId: 'stokvel-493c3',
    authDomain: 'stokvel-493c3.firebaseapp.com',
    storageBucket: 'stokvel-493c3.appspot.com',
    measurementId: 'G-6LM1Q6W2KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbC5CuCyRdrxlvtwhKd2GBQJwpAGrZJKg',
    appId: '1:580821940359:android:867f7841816b325cc92022',
    messagingSenderId: '580821940359',
    projectId: 'stokvel-493c3',
    storageBucket: 'stokvel-493c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKh7-lMynaf57_x5WOXmkJa14uvM9Aqw',
    appId: '1:580821940359:ios:57b9ac3905b4ab06c92022',
    messagingSenderId: '580821940359',
    projectId: 'stokvel-493c3',
    storageBucket: 'stokvel-493c3.appspot.com',
    iosBundleId: 'com.example.stokvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQKh7-lMynaf57_x5WOXmkJa14uvM9Aqw',
    appId: '1:580821940359:ios:19b1789cee3a8ee3c92022',
    messagingSenderId: '580821940359',
    projectId: 'stokvel-493c3',
    storageBucket: 'stokvel-493c3.appspot.com',
    iosBundleId: 'com.example.stokvel.RunnerTests',
  );
}
